### ISSUE TITLE
Bug Report: `FieldError: type Nothing has no field ast_transforms` on `lazy_startup_init!()` — broken on Julia v1.12, works on v1.11

### ISSUE THREAD

**Issue by singularitti** [wangl-cc/LazyStartup.jl#13]
Calling `lazy_startup_init!()` from `~/.julia/config/startup.jl` triggers a `FieldError` on Julia v1.12 (beta and release candidates). This used to work on Julia v1.11 and earlier. The error appears to stem from changes in Julia’s internal compiler API.

## Steps to Reproduce

1. On Julia v1.12 (beta/rc), configure `~/.julia/config/startup.jl` as:
   ```julia
   using LazyStartup: lazy_startup_init!, @lazy_startup
   lazy_startup_init!()
   ```
2. Launch Julia.

## Observed Behavior

```julia
ERROR: LoadError: FieldError: type Nothing has no field `ast_transforms`; Nothing has no fields at all.
Stacktrace:
 [1] getproperty(x::Nothing, f::Symbol)
   @ Base ./Base_compiler.jl:54
 [2] __current_ast_transforms()
   @ LazyStartup ~/.julia/packages/LazyStartup/pBReP/src/LazyStartup.jl:165
 [3] lazy_startup_init!()
   @ LazyStartup ~/.julia/packages/LazyStartup/pBReP/src/LazyStartup.jl:186
 [4] top-level scope
   @ ~/.julia/config/startup.jl:2
```

## Expected Behavior

Should initialize without error, as it does on Julia v1.11 and earlier.

## Regression

- ✅ Works on Julia v1.11.x and below  
- ❌ Fails on Julia v1.12.0-beta and v1.12.0-rc

## Environment

- **Julia version:** v1.12.0-beta / v1.12.0-rc (fails); v1.11.x (works)
- **LazyStartup.jl version:** v0.2.0
- **OS:** macOS 15.5 (24F74)

```julia
Julia Version 1.12.0-rc1
Commit 228edd6610b (2025-07-12 20:11 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 14 × Apple M4 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m4)
  GC: Built with stock GC
```
